apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

def DEFAULT_COMPILE_SDK_VERSION = 34
def DEFAULT_MIN_SDK_VERSION = 21
def DEFAULT_TARGET_SDK_VERSION = 34

def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0'
    }
}

android {
    buildFeatures {
        aidl = true
    }
    compileSdk safeExtGet('compileSdkVersion', DEFAULT_COMPILE_SDK_VERSION)
    defaultConfig {
        minSdk safeExtGet('minSdkVersion', DEFAULT_MIN_SDK_VERSION)
        targetSdk safeExtGet('targetSdkVersion', DEFAULT_TARGET_SDK_VERSION)
        versionCode 1
        versionName '1.0'
        buildConfigField('boolean', 'openvpn3', 'true')
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    lint {
        abortOnError false
    }
    sourceSets {
        main {
            java {
                srcDirs = ['src/main/java', 'src/ui/java']
            }
            res {
                srcDirs = ['src/main/res', 'src/ui/res']
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', includes: ['*.jar'])
    implementation 'androidx.annotation:annotation:1.3.0'
    implementation 'androidx.core:core:1.6.0'
    implementation 'androidx.appcompat:appcompat:1.3.1'
}
